// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2024, , Inc. All rights reserved.

#pragma once

#include "ck_tile/core.hpp"
#include "ck_tile/host/kernel_launch.hpp"
#include "ck_tile/ops/fused_moe_2stage/kernel/fmoe_2stage_kernel.hpp"
#include "fused_moe_quant_mode.hpp"

#include <string>

// runtime args
struct fused_moegemm_stage1_args : public ck_tile::FusedMoeStage1HostArgs
{
};

struct fused_moegemm_stage2_args : public ck_tile::FusedMoeStage2HostArgs
{
};

// This is the public API, will be generated by script
struct fused_moegemm_2stage_traits
{
    std::string prec_i;  // input precision
    std::string prec_w;  // weight precision
    std::string prec_o;  // output precision
    std::string prec_st; // token scale data type
    std::string prec_sw; // weight scale data type
    std::string prec_sq; // smooth quant scale
    std::string prec_zp; // zero points data type
    int block_m;
    int activation;  // 0:gelu, 1:silu
    int gate_only;   // 0:g1u0, 1:g1u1
    fused_quant_mode fused_quant;
    int solution_id;
};

float fused_moegemm_stage1(fused_moegemm_2stage_traits, fused_moegemm_stage1_args, const ck_tile::stream_config&);

float fused_moegemm_stage2(fused_moegemm_2stage_traits, fused_moegemm_stage2_args, const ck_tile::stream_config&);
