// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, , Inc. All rights reserved.

#pragma once

#include "ck_tile/core.hpp"
#include "ck_tile/core/numeric/type_convert.hpp"
#include "ck_tile/host/kernel_launch.hpp"
#include "ck_tile/ops/rmsnorm2d.hpp"
#include <hip/hip_bf16.h>
#include <hipcub/hipcub.hpp>
#include <cstdint>
#include <string>

template <typename InType,
          typename OutType,
          typename SmoothScaleDataType_,
          typename YScaleDataType_>
struct RmsnormTypeConfig;

template <typename OutType, typename SmoothScaleDataType_, typename YScaleDataType_>
struct RmsnormTypeConfig<ck_tile::half_t, OutType, SmoothScaleDataType_, YScaleDataType_>
{
    using XDataType           = ck_tile::half_t;
    using YDataType           = OutType;
    using GammaDataType       = ck_tile::half_t;
    using InvRmsDataType      = ck_tile::half_t;
    using UnquantYDataType    = ck_tile::half_t;
    using ComputeDataType     = float;
    using SmoothScaleDataType = SmoothScaleDataType_;
    using YScaleDataType      = YScaleDataType_;
};

template <typename OutType, typename SmoothScaleDataType_, typename YScaleDataType_>
struct RmsnormTypeConfig<ck_tile::bf16_t, OutType, SmoothScaleDataType_, YScaleDataType_>
{
    using XDataType           = ck_tile::bf16_t;
    using YDataType           = OutType;
    using GammaDataType       = ck_tile::bf16_t;
    using InvRmsDataType      = ck_tile::bf16_t;
    using UnquantYDataType    = ck_tile::bf16_t;
    using ComputeDataType     = float;
    using SmoothScaleDataType = SmoothScaleDataType_;
    using YScaleDataType      = YScaleDataType_;
};

// runtime args
struct rmsnorm2d_fwd_args : public ck_tile::Rmsnorm2dFwdHostArgs
{
};

template <typename Traits_>
float rmsnorm2d_fwd_(const ck_tile::stream_config& s, rmsnorm2d_fwd_args a);

// This is the public API, will be generated by script
struct rmsnorm2d_fwd_traits
{
    std::string prec_i; // input precision
    std::string prec_o; // output precision

    // if fused_quant == 1, need set prec_sm/prec_sy to proper string, otherwise can set
    // arbitrary(will skip check) if fused_quant == 2, need set prec_sy to proper string, otherwise
    // can set arbitrary(will skip check)
    std::string prec_sm; // x-scale, used for [1*N] input smooth quant
    std::string prec_sy; // y-scale, used for [M*1] output for next layer

    bool save_rms;
    bool save_unquant;
    int fused_add;   // 0:no-add, 1:pre-add-store, 2:pre-add
    int fused_quant; // 0:no-sweep, 1:smooth-dynamic-quant, 2:dynamic-quant
};

namespace rmsnorm2d_fwd_bf16_pras_detail {

template <int Width>
struct alignas(16) bf16_vec
{
    ck_tile::bf16_t data[Width];

    __device__ void add_assign_rn(const bf16_vec& other)
    {
#pragma unroll
        for(int i = 0; i < Width; ++i)
        {
            const float sum = ck_tile::type_convert<float>(data[i]) +
                              ck_tile::type_convert<float>(other.data[i]);
            data[i] = ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(sum);
        }
    }

    __device__ void mul_scale_rn(float scale)
    {
#pragma unroll
        for(int i = 0; i < Width; ++i)
        {
            const float prod = ck_tile::type_convert<float>(data[i]) * scale;
            data[i] = ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(prod);
        }
    }

    __device__ void mul_vec_rn(const bf16_vec& other)
    {
#pragma unroll
        for(int i = 0; i < Width; ++i)
        {
            const float prod = ck_tile::type_convert<float>(data[i]) *
                               ck_tile::type_convert<float>(other.data[i]);
            data[i] = ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(prod);
        }
    }

    __device__ float sum_squares() const
    {
        float result = 0.0f;
#pragma unroll
        for(int i = 0; i < Width; ++i)
        {
            const float value = ck_tile::type_convert<float>(data[i]);
            result += value * value;
        }
        return result;
    }
};

template <int Width>
static __global__ void rmsnorm2d_fwd_bf16_pras_kernel(const ck_tile::bf16_t* __restrict__ input,
                                                      const ck_tile::bf16_t* __restrict__ residual_in,
                                                      const ck_tile::bf16_t* __restrict__ gamma,
                                                      ck_tile::bf16_t* __restrict__ output,
                                                      ck_tile::bf16_t* __restrict__ residual_out,
                                                      float epsilon,
                                                      ck_tile::index_t num_rows,
                                                      ck_tile::index_t hidden_size)
{
    constexpr int kWidth = Width;
    const int row = blockIdx.x;
    if(row >= num_rows)
        return;

    const int vec_hidden_size = hidden_size / kWidth;
    float variance = 0.0f;

    auto* output_v = reinterpret_cast<bf16_vec<kWidth>*>(output);
    auto* residual_out_v = reinterpret_cast<bf16_vec<kWidth>*>(residual_out);
    auto* input_v = reinterpret_cast<const bf16_vec<kWidth>*>(input);
    auto* residual_in_v = reinterpret_cast<const bf16_vec<kWidth>*>(residual_in);
    auto* gamma_v = reinterpret_cast<const bf16_vec<kWidth>*>(gamma);

    for(int idx = threadIdx.x; idx < vec_hidden_size; idx += blockDim.x)
    {
        const int id = row * vec_hidden_size + idx;
        bf16_vec<kWidth> temp = input_v[id];
        temp.add_assign_rn(residual_in_v[id]);
        variance += temp.sum_squares();
        residual_out_v[id] = temp;
    }

    using BlockReduce = hipcub::BlockReduce<float, 256>;
    __shared__ typename BlockReduce::TempStorage reduce_store;
    __shared__ float s_variance;
    variance = BlockReduce(reduce_store).Reduce(variance, hipcub::Sum{}, blockDim.x);

    if(threadIdx.x == 0)
    {
        s_variance = rsqrtf(variance / hidden_size + epsilon);
    }
    __syncthreads();

    for(int idx = threadIdx.x; idx < vec_hidden_size; idx += blockDim.x)
    {
        const int id = row * vec_hidden_size + idx;
        bf16_vec<kWidth> temp = residual_out_v[id];
        temp.mul_scale_rn(s_variance);
        temp.mul_vec_rn(gamma_v[idx]);
        output_v[id] = temp;
    }
}

static __global__ void rmsnorm2d_fwd_bf16_pras_kernel_scalar(const ck_tile::bf16_t* __restrict__ input,
                                                             const ck_tile::bf16_t* __restrict__ residual_in,
                                                             const ck_tile::bf16_t* __restrict__ gamma,
                                                             ck_tile::bf16_t* __restrict__ output,
                                                             ck_tile::bf16_t* __restrict__ residual_out,
                                                             float epsilon,
                                                             ck_tile::index_t num_rows,
                                                             ck_tile::index_t hidden_size)
{
    const int row = blockIdx.x;
    if(row >= num_rows)
        return;

    float variance = 0.0f;
    for(int idx = threadIdx.x; idx < hidden_size; idx += blockDim.x)
    {
        const int id = row * hidden_size + idx;
        const float sum = ck_tile::type_convert<float>(input[id]) +
                          ck_tile::type_convert<float>(residual_in[id]);
        const auto added =
            ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(sum);
        residual_out[id] = added;
        const float value = ck_tile::type_convert<float>(added);
        variance += value * value;
    }

    using BlockReduce = hipcub::BlockReduce<float, 256>;
    __shared__ typename BlockReduce::TempStorage reduce_store;
    __shared__ float s_variance;
    variance = BlockReduce(reduce_store).Reduce(variance, hipcub::Sum{}, blockDim.x);

    if(threadIdx.x == 0)
    {
        s_variance = rsqrtf(variance / hidden_size + epsilon);
    }
    __syncthreads();

    for(int idx = threadIdx.x; idx < hidden_size; idx += blockDim.x)
    {
        const int id = row * hidden_size + idx;
        const float scaled = ck_tile::type_convert<float>(residual_out[id]) * s_variance;
        const auto rounded_scaled =
            ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(scaled);
        const float weighted = ck_tile::type_convert<float>(rounded_scaled) *
                               ck_tile::type_convert<float>(gamma[idx]);
        output[id] = ck_tile::float_to_bf16<ck_tile::bf16_rounding_mode::standard_asm>(weighted);
    }
}

inline bool use_bf16_pras_specialized(const rmsnorm2d_fwd_traits& t, const rmsnorm2d_fwd_args& a)
{
    const bool supported_hidden_size = a.n == 1024 || a.n == 2048 || a.n == 2560 || a.n == 4096 ||
                                       a.n == 5120 || a.n == 7168 || a.n == 8192;
    return t.prec_i == "bf16" && t.prec_o == "bf16" && t.fused_add == 1 && t.fused_quant == 0 &&
           !t.save_rms && !t.save_unquant && supported_hidden_size && a.x_stride == a.n &&
           a.xr_stride == a.n && a.y_stride == a.n && a.yr_stride == a.n && a.p_x != nullptr &&
           a.p_x_residual != nullptr && a.p_gamma != nullptr && a.p_y != nullptr &&
           a.p_y_residual != nullptr;
}

inline ck_tile::index_t select_bf16_pras_block_size(ck_tile::index_t n)
{
    switch(n)
    {
    case 1024:
    case 2048:
    case 2560:
    case 4096:
    case 5120:
    case 7168:
    case 8192:
    default:
        return 256;
    }
}

inline float try_rmsnorm2d_fwd_bf16_pras_specialized(const rmsnorm2d_fwd_traits& t,
                                                     const rmsnorm2d_fwd_args& a,
                                                     const ck_tile::stream_config& s)
{
    if(!use_bf16_pras_specialized(t, a))
        return -1;

    const dim3 grids(a.m);
    const dim3 blocks(select_bf16_pras_block_size(a.n));

    if(s.log_level_ > 0)
        std::cout << ", rmsnorm2d_fwd_bf16_pras_specialized" << std::flush;

    return ck_tile::launch_kernel(
        s,
        [=](const ck_tile::stream_config& sc) {
            rmsnorm2d_fwd_bf16_pras_kernel_scalar<<<grids, blocks, 0, sc.stream_id_>>>(
                static_cast<const ck_tile::bf16_t*>(a.p_x),
                static_cast<const ck_tile::bf16_t*>(a.p_x_residual),
                static_cast<const ck_tile::bf16_t*>(a.p_gamma),
                static_cast<ck_tile::bf16_t*>(a.p_y),
                static_cast<ck_tile::bf16_t*>(a.p_y_residual),
                a.epsilon,
                a.m,
                a.n);
        });
}

} // namespace rmsnorm2d_fwd_bf16_pras_detail

float rmsnorm2d_fwd(rmsnorm2d_fwd_traits, rmsnorm2d_fwd_args, const ck_tile::stream_config&);
