// !!! This is a file automatically generated by hipify!!!
#include <ATen/dtk_macros.h>
#include "hip/hip_runtime.h"
// SPDX-License-Identifier: MIT
// Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.

#pragma once

#include "jenga_bwd_dq_policy.hpp"

namespace ck_tile {
namespace example {
namespace jenga {

template <typename Problem, typename Policy = JengaBwdDqDefaultPolicy, bool FastOnly = false>
struct JengaBwdDqPipeline
{
    using QDataType     = typename Problem::QDataType;
    using KDataType     = typename Problem::KDataType;
    using VDataType     = typename Problem::VDataType;
    using OGradDataType = typename Problem::OGradDataType;
    using DQDataType    = typename Problem::DQDataType;
    using AccDataType   = typename Problem::AccDataType;

    static constexpr index_t BlockM          = Problem::BlockM;
    static constexpr index_t BlockN          = Problem::BlockN;
    static constexpr index_t HeadDim         = Problem::HeadDim;
    static constexpr index_t MaxNnz          = Problem::MaxNnz;
    static constexpr index_t ThreadsPerBlock = Policy::template GetBlockSize<Problem>();
    static constexpr index_t ThreadSpan      = Policy::template GetThreadLinearSpan<Problem>();
    static constexpr index_t DsSpan          = BlockM * BlockN;
    static constexpr index_t KSpan           = BlockN * HeadDim;
    static constexpr index_t ElemsPerThread =
        integer_divide_ceil(ThreadSpan, ThreadsPerBlock);
    static constexpr const char* name =
        FastOnly ? "qk_mmac_qdo_kv_db_dqreg_fast_lut" : "qk_mmac_qdo_kv_ds_dq_mmac_lut";

    CK_TILE_HOST_DEVICE static constexpr index_t GetSmemSize()
    {
        return Policy::template GetSmemSize<Problem>();
    }

    template <typename QBlockWindow,
              typename KTensorView,
              typename VTensorView,
              typename OGradBlockWindow,
              typename DeltaBlockWindow,
              typename LseBlockWindow,
              typename DQBlockWindow>
    CK_TILE_DEVICE void operator()(const QBlockWindow& q_block_window,
                                   const KTensorView& k_tensor_view,
                                   const VTensorView& v_tensor_view,
                                   const OGradBlockWindow& dout_block_window,
                                   const DeltaBlockWindow& delta_block_window,
                                   const LseBlockWindow& lse_block_window,
                                   DQBlockWindow& dq_block_window,
                                   const jenga_bwd_dq_args& a,
                                   void*) const
    {
        static_assert(Policy::template IsSupported<Problem>());

        const auto q_window =
            make_tile_window(q_block_window, Policy::template MakeQOGradDQBlockTileDistribution<Problem>());
        const auto dout_window = make_tile_window(
            dout_block_window, Policy::template MakeQOGradDQBlockTileDistribution<Problem>());
        auto dq_window =
            make_tile_window(dq_block_window, Policy::template MakeQOGradDQBlockTileDistribution<Problem>());

        const index_t start_m = static_cast<index_t>(blockIdx.x);
        const index_t off_hz  = static_cast<index_t>(blockIdx.y);
        const index_t batch_id = off_hz / a.nhead;
        const index_t seqlen   = static_cast<index_t>(a.seqlens[batch_id]);

        if(start_m * BlockM >= seqlen)
        {
            return;
        }

        const QDataType* q        = q_window.get_bottom_tensor_view().get_buffer_view().p_data_;
        const KDataType* k        = k_tensor_view.get_buffer_view().p_data_;
        const VDataType* v        = v_tensor_view.get_buffer_view().p_data_;
        const OGradDataType* dout = dout_window.get_bottom_tensor_view().get_buffer_view().p_data_;
        const float* deltas =
            delta_block_window.get_bottom_tensor_view().get_buffer_view().p_data_;
        const float* lse = lse_block_window.get_bottom_tensor_view().get_buffer_view().p_data_;
        DQDataType* dq   = dq_window.get_bottom_tensor_view().get_buffer_view().p_data_;
        const index_t num_q_blocks = integer_divide_ceil(a.seqlen_q, BlockM);
        const int num_active       = a.lut_size[off_hz * num_q_blocks + start_m];
        const float qk_scale       = a.sm_scale * 1.4426950408889634f;

        __shared__ QDataType q_lds[FastOnly ? 0 : ThreadSpan];
        __shared__ KDataType k_lds[(FastOnly ? 2 : 1) * KSpan];
        __shared__ VDataType v_lds[(FastOnly ? 2 : 1) * KSpan];
        constexpr auto gemm_0 = Policy::template GetQKBlockGemm<Problem>();
        constexpr auto gemm_0_reg = Policy::template GetQKRegBlockGemm<Problem>();
        constexpr auto gemm_2 = Policy::template GetDPBlockGemm<Problem>();
        constexpr auto gemm_4_reg = Policy::template GetDQRegBlockGemm<Problem>();

        auto dq_block_tile = decltype(gemm_4_reg)::MakeCBlockTile();
        tile_elementwise_inout([](auto& x) { x = 0.0f; }, dq_block_tile);

        auto dout_bh_view = make_naive_tensor_view<address_space_enum::global>(
            dout,
            make_tuple(a.seqlen_q, number<HeadDim>{}),
            make_tuple(a.stride_dom, a.stride_dok),
            number<1>{},
            number<8>{});
        auto dout_reg_window =
            make_tile_window(dout_bh_view,
                             make_tuple(number<BlockM>{}, number<HeadDim>{}),
                             {start_m * BlockM, 0},
                             Policy::template MakeOGradRegBlockDistribution<Problem>());
        const auto dout_reg_tile = load_tile(dout_reg_window);
        const auto q_block_tile  = load_tile(q_window);
        if constexpr(!FastOnly)
        {
            constexpr auto qdo_lds_desc = make_naive_tensor_descriptor(
                make_tuple(number<BlockM>{}, number<HeadDim>{}),
                make_tuple(number<HeadDim>{}, number<1>{}),
                number<8>{},
                number<1>{});
            auto q_lds_2d_view = make_tensor_view<address_space_enum::lds>(q_lds, qdo_lds_desc);
            auto q_lds_store_window =
                make_tile_window(q_lds_2d_view,
                                 make_tuple(number<BlockM>{}, number<HeadDim>{}),
                                 {0, 0},
                                 Policy::template MakeQOGradDQBlockTileDistribution<Problem>());
            store_tile(q_lds_store_window, q_block_tile);
            block_sync_lds();
        }

        if(num_active == MaxNnz && seqlen % BlockM == 0 && seqlen % BlockN == 0)
        {
            constexpr auto kv_lds_desc = make_naive_tensor_descriptor(
                make_tuple(number<BlockN>{}, number<HeadDim>{}),
                make_tuple(number<HeadDim>{}, number<1>{}),
                number<8>{},
                number<1>{});
            auto k_bh_view = make_naive_tensor_view<address_space_enum::global>(
                k + off_hz * a.stride_kz,
                make_tuple(a.seqlen_q, number<HeadDim>{}),
                make_tuple(a.stride_kn, a.stride_kk),
                number<1>{},
                number<8>{});
            auto v_bh_view = make_naive_tensor_view<address_space_enum::global>(
                v + off_hz * a.stride_vz,
                make_tuple(a.seqlen_q, number<HeadDim>{}),
                make_tuple(a.stride_vn, a.stride_vk),
                number<1>{},
                number<8>{});
            const auto load_kv_block = [&](index_t lut_i, index_t lds_buf) {
                const int block_idx =
                    a.lut[off_hz * a.stride_lutz + start_m * a.stride_lutm + lut_i * a.stride_lutk];
                const index_t start_n = static_cast<index_t>(block_idx) * BlockN;

                auto kv_lds_view =
                    make_tensor_view<address_space_enum::lds>(k_lds + lds_buf * KSpan, kv_lds_desc);
                auto v_lds_view =
                    make_tensor_view<address_space_enum::lds>(v_lds + lds_buf * KSpan, kv_lds_desc);
                auto kv_lds_store_window =
                    make_tile_window(kv_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                auto v_lds_store_window =
                    make_tile_window(v_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                auto k_dram_window =
                    make_tile_window(k_bh_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {start_n, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                auto v_dram_window =
                    make_tile_window(v_bh_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {start_n, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                const auto k_tile = load_tile(k_dram_window);
                store_tile(kv_lds_store_window, k_tile);
                const auto v_tile = load_tile(v_dram_window);
                store_tile(v_lds_store_window, v_tile);
            };

            if constexpr(FastOnly)
            {
                load_kv_block(0, 0);
            }

            for(index_t i = 0; i < MaxNnz; ++i)
            {
                const int block_idx =
                    a.lut[off_hz * a.stride_lutz + start_m * a.stride_lutm + i * a.stride_lutk];
                const index_t start_n = static_cast<index_t>(block_idx) * BlockN;
                const bool has_text_bias = a.text_amp != 0.0f && block_idx >= a.text_block_start;
                const index_t lds_buf = FastOnly ? (i & 1) : 0;

                if constexpr(FastOnly)
                {
                    if(i + 1 < MaxNnz)
                    {
                        load_kv_block(i + 1, lds_buf ^ 1);
                    }
                    block_sync_lds();
                }

                if constexpr(!FastOnly)
                {
                    load_kv_block(i, 0);
                    block_sync_lds();
                }

                constexpr auto k_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<BlockN>{}, number<HeadDim>{}),
                    make_tuple(number<HeadDim>{}, number<1>{}),
                    number<8>{},
                    number<1>{});

                auto k_lds_view =
                    make_tensor_view<address_space_enum::lds>(k_lds + lds_buf * KSpan, k_lds_desc);
                auto k_gemm_window =
                    make_tile_window(k_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0});

                auto qk_block_tile = decltype(gemm_0)::MakeCBlockTile();
                tile_elementwise_inout([](auto& x) { x = 0.0f; }, qk_block_tile);
                if constexpr(FastOnly)
                {
                    gemm_0_reg(qk_block_tile, q_block_tile, k_gemm_window);
                }
                else
                {
                    constexpr auto q_lds_desc = make_naive_tensor_descriptor(
                        make_tuple(number<BlockM>{}, number<HeadDim>{}),
                        make_tuple(number<HeadDim>{}, number<1>{}),
                        number<8>{},
                        number<1>{});
                    auto q_lds_view =
                        make_tensor_view<address_space_enum::lds>(q_lds, q_lds_desc);
                    auto q_gemm_window = make_tile_window(
                        q_lds_view, make_tuple(number<BlockM>{}, number<HeadDim>{}), {0, 0});
                    gemm_0(qk_block_tile, q_gemm_window, k_gemm_window);
                }

                auto v_lds_view =
                    make_tensor_view<address_space_enum::lds>(v_lds + lds_buf * KSpan, kv_lds_desc);
                auto v_gemm_window =
                    make_tile_window(v_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0});

                auto v_reg_window =
                    make_tile_window(v_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeVRegBlockDistribution<Problem>());

                const auto v_reg_tile    = load_tile(v_reg_window);
                auto dp_block_tile       = gemm_2(dout_reg_tile, v_reg_tile);
                auto ds_reg_tile = tile_elementwise_in(
                    [](auto) { return type_convert<QDataType>(0.0f); }, dp_block_tile);

                constexpr index_t threads_per_row = ThreadsPerBlock / BlockM;
                const index_t row_id = start_m * BlockM + (ck_tile::get_thread_id() / threads_per_row);
                const float row_lse = lse[off_hz * a.stride_lz + row_id * a.stride_lm];
                const float delta   = deltas[off_hz * a.stride_dz + row_id * a.stride_dm];

                sweep_tile(dp_block_tile, [&](auto idx) {
                    float qk              = qk_block_tile[idx] * qk_scale;
                    if(has_text_bias)
                    {
                        qk += a.text_amp;
                    }

                    const float p       = exp2f(qk - row_lse);
                    const float ds      = p * (dp_block_tile[idx] - delta);
                    ds_reg_tile(idx) = type_convert<QDataType>(ds);
                });

                constexpr auto kt_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<HeadDim>{}, number<BlockN>{}),
                    make_tuple(number<1>{}, number<HeadDim>{}));

                auto kt_lds_view = make_tensor_view<address_space_enum::lds>(
                    k_lds + lds_buf * KSpan, kt_lds_desc);
                auto kt_gemm_window =
                    make_tile_window(kt_lds_view,
                                     make_tuple(number<HeadDim>{}, number<BlockN>{}),
                                     {0, 0});

                gemm_4_reg(dq_block_tile, ds_reg_tile, kt_gemm_window);

                block_sync_lds();
            }

            sweep_tile(dq_block_tile, [&](auto idx) {
                const auto x_indices =
                    get_x_indices_from_distributed_indices(dq_block_tile.get_tile_distribution(), idx);
                const index_t local_m = x_indices[number<0>{}];
                const index_t d       = x_indices[number<1>{}];
                const index_t row_id  = start_m * BlockM + local_m;
                dq[row_id * a.stride_dqm + d * a.stride_dqk] =
                    type_convert<DQDataType>(dq_block_tile[idx] * a.sm_scale);
            });
            return;
        }

        if constexpr(FastOnly)
        {
            return;
        }
        else
        {
            __shared__ QDataType ds_lds[DsSpan];
            constexpr auto gemm_4 = Policy::template GetDQBlockGemm<Problem>();

            for(index_t i = 0; i < MaxNnz; ++i)
            {
                const bool has_active_block = i < static_cast<index_t>(num_active);
                int block_idx               = 0;
                index_t start_n             = 0;
                bool has_text_bias          = false;

                if(has_active_block)
                {
                    block_idx =
                        a.lut[off_hz * a.stride_lutz + start_m * a.stride_lutm + i * a.stride_lutk];
                    start_n = static_cast<index_t>(block_idx) * BlockN;
                    has_text_bias = a.text_amp != 0.0f && block_idx >= a.text_block_start;
                }
                constexpr auto kv_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<BlockN>{}, number<HeadDim>{}),
                    make_tuple(number<HeadDim>{}, number<1>{}));
                auto kv_lds_view = make_tensor_view<address_space_enum::lds>(k_lds, kv_lds_desc);
                auto v_lds_view  = make_tensor_view<address_space_enum::lds>(v_lds, kv_lds_desc);
                auto kv_lds_store_window =
                    make_tile_window(kv_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                auto v_lds_store_window =
                    make_tile_window(v_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeKVBlockTileDistribution<Problem>());
                const bool full_kv_block = has_active_block && start_n + BlockN <= seqlen;

                if(full_kv_block)
                {
                    auto k_bh_view = make_naive_tensor_view<address_space_enum::global>(
                        k + off_hz * a.stride_kz,
                        make_tuple(a.seqlen_q, number<HeadDim>{}),
                        make_tuple(a.stride_kn, a.stride_kk),
                        number<1>{},
                        number<8>{});
                    auto k_dram_window =
                        make_tile_window(k_bh_view,
                                         make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                         {start_n, 0},
                                         Policy::template MakeKVBlockTileDistribution<Problem>());
                    const auto k_tile = load_tile(k_dram_window);
                    store_tile(kv_lds_store_window, k_tile);
                }
                else
                {
                    for(index_t k_elem = ck_tile::get_thread_id(); k_elem < KSpan;
                        k_elem += ThreadsPerBlock)
                    {
                        const index_t local_n = k_elem / HeadDim;
                        const index_t d       = k_elem % HeadDim;
                        const index_t col     = start_n + local_n;

                        if(has_active_block && col < seqlen)
                        {
                            k_lds[k_elem] =
                                k[off_hz * a.stride_kz + col * a.stride_kn + d * a.stride_kk];
                        }
                        else
                        {
                            k_lds[k_elem] = type_convert<KDataType>(0.0f);
                        }
                    }
                }

                block_sync_lds();

                constexpr auto q_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<BlockM>{}, number<HeadDim>{}),
                    make_tuple(number<HeadDim>{}, number<1>{}));
                constexpr auto k_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<BlockN>{}, number<HeadDim>{}),
                    make_tuple(number<HeadDim>{}, number<1>{}));

                auto q_lds_view = make_tensor_view<address_space_enum::lds>(q_lds, q_lds_desc);
                auto k_lds_view = make_tensor_view<address_space_enum::lds>(k_lds, k_lds_desc);
                auto q_gemm_window =
                    make_tile_window(q_lds_view,
                                     make_tuple(number<BlockM>{}, number<HeadDim>{}),
                                     {0, 0});
                auto k_gemm_window =
                    make_tile_window(k_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0});

                auto qk_block_tile = decltype(gemm_0)::MakeCBlockTile();
                tile_elementwise_inout([](auto& x) { x = 0.0f; }, qk_block_tile);
                gemm_0(qk_block_tile, q_gemm_window, k_gemm_window);

                if(full_kv_block)
                {
                    auto v_bh_view = make_naive_tensor_view<address_space_enum::global>(
                        v + off_hz * a.stride_vz,
                        make_tuple(a.seqlen_q, number<HeadDim>{}),
                        make_tuple(a.stride_vn, a.stride_vk),
                        number<1>{},
                        number<8>{});
                    auto v_dram_window =
                        make_tile_window(v_bh_view,
                                         make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                         {start_n, 0},
                                         Policy::template MakeKVBlockTileDistribution<Problem>());
                    const auto v_tile = load_tile(v_dram_window);
                    store_tile(v_lds_store_window, v_tile);
                }
                else
                {
                    sweep_tile(qk_block_tile, [&](auto idx) {
                        const auto x_indices =
                            get_x_indices_from_distributed_indices(qk_block_tile.get_tile_distribution(), idx);
                        const index_t local_m = x_indices[number<0>{}];
                        const index_t local_n = x_indices[number<1>{}];
                        ds_lds[local_m * BlockN + local_n] =
                            type_convert<QDataType>(qk_block_tile[idx] * qk_scale);
                    });

                    block_sync_lds();

                    for(index_t v_elem = ck_tile::get_thread_id(); v_elem < KSpan;
                        v_elem += ThreadsPerBlock)
                    {
                        const index_t local_n = v_elem / HeadDim;
                        const index_t d       = v_elem % HeadDim;
                        const index_t col     = start_n + local_n;

                        if(has_active_block && col < seqlen)
                        {
                            v_lds[v_elem] = type_convert<VDataType>(
                                v[off_hz * a.stride_vz + col * a.stride_vn + d * a.stride_vk]);
                        }
                        else
                        {
                            v_lds[v_elem] = type_convert<VDataType>(0.0f);
                        }
                    }

                    block_sync_lds();

                    for(index_t ds_elem = ck_tile::get_thread_id(); ds_elem < DsSpan;
                        ds_elem += ThreadsPerBlock)
                    {
                        const index_t local_m = ds_elem / BlockN;
                        const index_t local_n = ds_elem % BlockN;
                        const index_t ds_row  = start_m * BlockM + local_m;
                        const index_t ds_col  = start_n + local_n;
                        float ds              = 0.0f;

                        if(has_active_block && ds_row < seqlen && ds_col < seqlen)
                        {
                            float dp = 0.0f;

                            for(index_t kd = 0; kd < HeadDim; ++kd)
                            {
                                const float do_val = type_convert<float>(
                                    dout[ds_row * a.stride_dom + kd * a.stride_dok]);
                                const float v_val =
                                    type_convert<float>(v_lds[local_n * HeadDim + kd]);
                                dp += do_val * v_val;
                            }

                            float qk = type_convert<float>(ds_lds[ds_elem]);
                            if(has_text_bias)
                            {
                                qk += a.text_amp;
                            }

                            const float row_lse = lse[off_hz * a.stride_lz + ds_row * a.stride_lm];
                            const float delta   = deltas[off_hz * a.stride_dz + ds_row * a.stride_dm];
                            const float p       = exp2f(qk - row_lse);
                            ds                  = p * (dp - delta);
                        }

                        ds_lds[ds_elem] = type_convert<QDataType>(ds);
                    }

                    block_sync_lds();
                }

                block_sync_lds();

                auto v_reg_window =
                    make_tile_window(v_lds_view,
                                     make_tuple(number<BlockN>{}, number<HeadDim>{}),
                                     {0, 0},
                                     Policy::template MakeVRegBlockDistribution<Problem>());

                const auto v_reg_tile    = load_tile(v_reg_window);
                auto dp_block_tile       = gemm_2(dout_reg_tile, v_reg_tile);

                sweep_tile(dp_block_tile, [&](auto idx) {
                    const auto x_indices =
                        get_x_indices_from_distributed_indices(dp_block_tile.get_tile_distribution(), idx);
                    const index_t local_m = x_indices[number<0>{}];
                    const index_t local_n = x_indices[number<1>{}];
                    const index_t ds_row  = start_m * BlockM + local_m;
                    const index_t ds_col  = start_n + local_n;
                    float ds              = 0.0f;

                    if(has_active_block && ds_row < seqlen && ds_col < seqlen)
                    {
                        float qk = qk_block_tile[idx] * qk_scale;
                        if(has_text_bias)
                        {
                            qk += a.text_amp;
                        }

                        const float row_lse = lse[off_hz * a.stride_lz + ds_row * a.stride_lm];
                        const float delta   = deltas[off_hz * a.stride_dz + ds_row * a.stride_dm];
                        const float p       = exp2f(qk - row_lse);
                        ds                  = p * (dp_block_tile[idx] - delta);
                    }

                    ds_lds[local_m * BlockN + local_n] = type_convert<QDataType>(ds);
                });

                block_sync_lds();

                constexpr auto ds_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<BlockM>{}, number<BlockN>{}),
                    make_tuple(number<BlockN>{}, number<1>{}));
                constexpr auto kt_lds_desc = make_naive_tensor_descriptor(
                    make_tuple(number<HeadDim>{}, number<BlockN>{}),
                    make_tuple(number<1>{}, number<HeadDim>{}));

                auto ds_lds_view =
                    make_tensor_view<address_space_enum::lds>(ds_lds, ds_lds_desc);
                auto kt_lds_view =
                    make_tensor_view<address_space_enum::lds>(k_lds, kt_lds_desc);
                auto ds_gemm_window =
                    make_tile_window(ds_lds_view,
                                     make_tuple(number<BlockM>{}, number<BlockN>{}),
                                     {0, 0});
                auto kt_gemm_window =
                    make_tile_window(kt_lds_view,
                                     make_tuple(number<HeadDim>{}, number<BlockN>{}),
                                     {0, 0});

                gemm_4(dq_block_tile, ds_gemm_window, kt_gemm_window);

                block_sync_lds();
            }

            sweep_tile(dq_block_tile, [&](auto idx) {
                const auto x_indices =
                    get_x_indices_from_distributed_indices(dq_block_tile.get_tile_distribution(), idx);
                const index_t local_m = x_indices[number<0>{}];
                const index_t d       = x_indices[number<1>{}];
                const index_t row_id  = start_m * BlockM + local_m;
                if(row_id < seqlen)
                {
                    dq[row_id * a.stride_dqm + d * a.stride_dqk] =
                        type_convert<DQDataType>(dq_block_tile[idx] * a.sm_scale);
                }
            });
        }
    }
};



} // namespace jenga
} // namespace example
} // namespace ck_tile
