// !!! This is a file automatically generated by hipify!!!
#include <ATen/dtk_macros.h>
// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2022, , Inc. All rights reserved.

#pragma once

#include <hip/hip_runtime.h>

#include "ck/ck.hpp"
#include "ck/stream_config.hpp"
#include "ck/host_utility/hip_check_error.hpp"

template <typename... Args, typename F>
float launch_and_time_kernel(const StreamConfig& stream_config,
                             F kernel,
                             dim3 grid_dim,
                             dim3 block_dim,
                             std::size_t lds_byte,
                             Args... args)
{
#if CK_TIME_KERNEL
    if(stream_config.time_kernel_)
    {
#if DEBUG_LOG
        printf("%s: grid_dim {%d, %d, %d}, block_dim {%d, %d, %d} \n",
               __func__,
               grid_dim.x,
               grid_dim.y,
               grid_dim.z,
               block_dim.x,
               block_dim.y,
               block_dim.z);
#endif

#ifndef CK_BUILD_ON_PERF_MODEL
        // do warmup
       hipLaunchKernelGGL(( kernel), dim3(grid_dim), dim3(block_dim), lds_byte, stream_config.stream_id_, args...);

        int niters = 10;
#else
        // only run once on perf model
        int niters = 1;
#endif

        hipEvent_t start, stop;

        hip_check_error(hipEventCreate(&start));
        hip_check_error(hipEventCreate(&stop));

        hip_check_error(hipEventRecord(start, stream_config.stream_id_));

        for(int i = 0; i < niters; ++i)
        {
           hipLaunchKernelGGL(( kernel), dim3(grid_dim), dim3(block_dim), lds_byte, stream_config.stream_id_, args...);
        }

        hip_check_error(hipEventRecord(stop, stream_config.stream_id_));
        hip_check_error(hipEventSynchronize(stop));

        float total_time = 0;

        hip_check_error(hipEventElapsedTime(&total_time, start, stop));

        return total_time / float(niters);
    }
    else
    {
       hipLaunchKernelGGL(( kernel), dim3(grid_dim), dim3(block_dim), lds_byte, stream_config.stream_id_, args...);

        return 0;
    }
#else
   hipLaunchKernelGGL(( kernel), dim3(grid_dim), dim3(block_dim), lds_byte, stream_config.stream_id_, args...);

    return 0;
#endif
}
